openapi: 3.0.1
info:
  title: Doctor Appointment System API
  description: REST API documentation for Doctor Appointment System
  contact:
    name: Hospital Admin
    url: https://www.hospital.com
    email: admin@hospital.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Development Server
paths: {}
components: {}
