apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
  namespace: hospital-management
data:
  application.properties: |
    # Database Configuration
    spring.datasource.url=jdbc:mysql://mysql-service:3306/doctor_appointment_db?createDatabaseIfNotExist=true
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    
    # HikariCP Configuration
    spring.datasource.hikari.maximum-pool-size=20
    spring.datasource.hikari.minimum-idle=5
    spring.datasource.hikari.idle-timeout=300000
    spring.datasource.hikari.pool-name=HikariCP-Hospital
    spring.datasource.hikari.max-lifetime=1200000
    spring.datasource.hikari.connection-timeout=20000
    spring.datasource.hikari.validation-timeout=5000
    spring.datasource.hikari.leak-detection-threshold=60000
    spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.hikari.auto-commit=true
    
    # JPA/Hibernate Configuration
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.properties.hibernate.jdbc.batch_size=20
    spring.jpa.properties.hibernate.order_inserts=true
    spring.jpa.properties.hibernate.order_updates=true
    
    # Logging Configuration
    logging.level.root=INFO
    logging.level.com.hospital=INFO
    logging.file.name=logs/application.log
    
    # Server Configuration
    server.port=8080
    management.endpoints.web.exposure.include=health,info,metrics
    management.endpoint.health.show-details=always

