apiVersion: v1
kind: Secret
metadata:
  name: hospital-secrets
  namespace: hospital-management
type: Opaque
data:
  # Base64 encoded values - change these in production
  # DB_USERNAME: cm9vdA== (root)
  # DB_PASSWORD: YWRtaW4= (admin)
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: hospital-management
type: Opaque
data:
  # Base64 encoded values
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_DATABASE: ZG9jdG9yX2FwcG9pbnRtZW50X2Ri

